### ISSUE TITLE
"How to use" is missing

### ISSUE THREAD

**Issue by earthquakesan** [big-data-europe/app-swarm-ui#1]
Was not able to feed it docker-compose.yml.
What is repository there? Tried to point both to 'https://github.com/big-data-europe/demo-integrator-ui' and 'https://github.com/big-data-europe/demo-integrator-ui.git'

Can't debug myself, cecton/mu-swarm-admin repo is private [docker-hub-link](https://hub.docker.com/r/cecton/mu-swarm-admin/)

Several things app should be able to tackle:
- There are external files (e.g. hadoop.env)
- Not all of the docker images are published on docker hub. It is not convenient to publish image such as 'frontend' or 'integrator-ui' in the repo.
- If icon is missing use default one?

My configuration:
- Title: myrepo
- Clone url: https://github.com/big-data-europe/demo-integrator-ui.git
- MD Icon name: icon_name
- http icon name: http://localhost/icon_name

I am quite confused by MD Icon name/http icon name. What are their purpose? Can you please make repo public, I can take a look myself then.

Stacktrace:

```
identifier_1 | 
identifier_1 | 12:47:03.471 [info]  POST /swarm/repositories/5763EEE3FC9F010008000001/pipelines
identifier_1 | keeping user_id
identifier_1 | "http://mu.semte.ch/sessions/20f8223e-3488-11e6-8aff-000000000000"
dispatcher_1 | Forwarding request to http://swarm/repositories/5763EEE3FC9F010008000001/pipelines
dispatcher_1 | 
dispatcher_1 | 12:47:03.474 [info]  POST /swarm/repositories/5763EEE3FC9F010008000001/pipelines
swarm_1      | Traceback (most recent call last):
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
swarm_1      |     return self.wsgi_app(environ, start_response)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
swarm_1      |     response = self.make_response(self.handle_exception(e))
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask_restful/__init__.py", line 271, in error_router
swarm_1      |     return original_handler(e)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
swarm_1      |     reraise(exc_type, exc_value, tb)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
swarm_1      |     raise value
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
swarm_1      |     response = self.full_dispatch_request()
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
swarm_1      |     rv = self.handle_user_exception(e)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask_restful/__init__.py", line 271, in error_router
swarm_1      |     return original_handler(e)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
swarm_1      |     reraise(exc_type, exc_value, tb)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
swarm_1      |     raise value
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
swarm_1      |     rv = self.dispatch_request()
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
swarm_1      |     return self.view_functions[rule.endpoint](**req.view_args)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask_restful/__init__.py", line 477, in wrapper
swarm_1      |     resp = resource(*args, **kwargs)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/views.py", line 84, in view
swarm_1      |     return self.dispatch_request(*args, **kwargs)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
swarm_1      |     resp = meth(*args, **kwargs)
swarm_1      |   File "/app/mu_semtech/pipeline.py", line 135, in post
swarm_1      |     self._update_database(repository, repository_id, project_id)
swarm_1      |   File "/app/mu_semtech/pipeline.py", line 73, in _update_database
swarm_1      |     repository['http://mu.semte.ch/vocabularies/ext/mdlIcon']\
swarm_1      | KeyError: 'http://mu.semte.ch/vocabularies/ext/mdlIcon'
swarm_1      | --------------------------------------------------------------------------------
swarm_1      | ERROR in api [/app/mu_semtech/api.py:32]:
swarm_1      | Exception during the error handling
swarm_1      | --------------------------------------------------------------------------------
swarm_1      | Traceback (most recent call last):
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
swarm_1      |     rv = self.dispatch_request()
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
swarm_1      |     return self.view_functions[rule.endpoint](**req.view_args)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask_restful/__init__.py", line 477, in wrapper
swarm_1      |     resp = resource(*args, **kwargs)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/views.py", line 84, in view
swarm_1      |     return self.dispatch_request(*args, **kwargs)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
swarm_1      |     resp = meth(*args, **kwargs)
swarm_1      |   File "/app/mu_semtech/pipeline.py", line 135, in post
swarm_1      |     self._update_database(repository, repository_id, project_id)
swarm_1      |   File "/app/mu_semtech/pipeline.py", line 73, in _update_database
swarm_1      |     repository['http://mu.semte.ch/vocabularies/ext/mdlIcon']\
swarm_1      | KeyError: 'http://mu.semte.ch/vocabularies/ext/mdlIcon'
swarm_1      | 
swarm_1      | During handling of the above exception, another exception occurred:
swarm_1      | 
swarm_1      | Traceback (most recent call last):
swarm_1      |   File "/app/mu_semtech/api.py", line 29, in handle_error
swarm_1      |     resp = self.make_response(data, code, headers)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask_restful/__init__.py", line 510, in make_response
swarm_1      |     resp = self.representations[mediatype](data, *args, **kwargs)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask_restful/representations/json.py", line 20, in output_json
swarm_1      |     dumped = dumps(data, **settings) + "\n"
swarm_1      |   File "/usr/local/lib/python3.4/json/__init__.py", line 237, in dumps
swarm_1      |     **kw).encode(obj)
swarm_1      |   File "/usr/local/lib/python3.4/json/encoder.py", line 194, in encode
swarm_1      |     chunks = list(chunks)
swarm_1      |   File "/usr/local/lib/python3.4/json/encoder.py", line 422, in _iterencode
swarm_1      |     yield from _iterencode_dict(o, _current_indent_level)
swarm_1      |   File "/usr/local/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
swarm_1      |     yield from chunks
swarm_1      |   File "/usr/local/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
swarm_1      |     yield from chunks
swarm_1      |   File "/usr/local/lib/python3.4/json/encoder.py", line 429, in _iterencode
swarm_1      |     o = _default(o)
swarm_1      |   File "/usr/local/lib/python3.4/json/encoder.py", line 173, in default
swarm_1      |     raise TypeError(repr(o) + " is not JSON serializable")
swarm_1      | TypeError: {'Internal Server Error', 'title'} is not JSON serializable
swarm_1      | --------------------------------------------------------------------------------
swarm_1      | ERROR in api [/app/mu_semtech/api.py:32]:
swarm_1      | Exception during the error handling
swarm_1      | --------------------------------------------------------------------------------
swarm_1      | Traceback (most recent call last):
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
swarm_1      |     response = self.full_dispatch_request()
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
swarm_1      |     rv = self.handle_user_exception(e)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask_restful/__init__.py", line 271, in error_router
swarm_1      |     return original_handler(e)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
swarm_1      |     reraise(exc_type, exc_value, tb)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
swarm_1      |     raise value
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
swarm_1      |     rv = self.dispatch_request()
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
swarm_1      |     return self.view_functions[rule.endpoint](**req.view_args)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask_restful/__init__.py", line 477, in wrapper
swarm_1      |     resp = resource(*args, **kwargs)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask/views.py", line 84, in view
swarm_1      |     return self.dispatch_request(*args, **kwargs)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
swarm_1      |     resp = meth(*args, **kwargs)
swarm_1      |   File "/app/mu_semtech/pipeline.py", line 135, in post
swarm_1      |     self._update_database(repository, repository_id, project_id)
swarm_1      |   File "/app/mu_semtech/pipeline.py", line 73, in _update_database
swarm_1      |     repository['http://mu.semte.ch/vocabularies/ext/mdlIcon']\
swarm_1      | KeyError: 'http://mu.semte.ch/vocabularies/ext/mdlIcon'
swarm_1      | 
swarm_1      | During handling of the above exception, another exception occurred:
swarm_1      | 
swarm_1      | Traceback (most recent call last):
swarm_1      |   File "/app/mu_semtech/api.py", line 29, in handle_error
swarm_1      |     resp = self.make_response(data, code, headers)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask_restful/__init__.py", line 510, in make_response
swarm_1      |     resp = self.representations[mediatype](data, *args, **kwargs)
swarm_1      |   File "/usr/local/lib/python3.4/site-packages/flask_restful/representations/json.py", line 20, in output_json
swarm_1      |     dumped = dumps(data, **settings) + "\n"
swarm_1      |   File "/usr/local/lib/python3.4/json/__init__.py", line 237, in dumps
swarm_1      |     **kw).encode(obj)
swarm_1      |   File "/usr/local/lib/python3.4/json/encoder.py", line 194, in encode
swarm_1      |     chunks = list(chunks)
swarm_1      |   File "/usr/local/lib/python3.4/json/encoder.py", line 422, in _iterencode
swarm_1      |     yield from _iterencode_dict(o, _current_indent_level)
swarm_1      |   File "/usr/local/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
swarm_1      |     yield from chunks
swarm_1      |   File "/usr/local/lib/python3.4/json/encoder.py", line 317, in _iterencode_list
swarm_1      |     yield from chunks
swarm_1      |   File "/usr/local/lib/python3.4/json/encoder.py", line 429, in _iterencode
swarm_1      |     o = _default(o)
swarm_1      |   File "/usr/local/lib/python3.4/json/encoder.py", line 173, in default
swarm_1      |     raise TypeError(repr(o) + " is not JSON serializable")
swarm_1      | TypeError: {'Internal Server Error', 'title'} is not JSON serializable
swarm_1      | 172.20.0.4 - - [17/Jun/2016 12:47:06] "POST /repositories/5763EEE3FC9F010008000001/pipelines HTTP/1.1" 500 -
dispatcher_1 | 
dispatcher_1 | 12:47:06.445 [info]  Sent 500 in 2970ms
identifier_1 | 
identifier_1 | 12:47:06.445 [info]  Sent 500 in 2974ms
```

**Comment by madnificent** [comment]
The repo is now published on our big-data-europe GitHub where you should have access.

The md_icon is a simpler way of specifying icons, as most people don't host their own icons (and it matches with the general UI).  We should improve this in the future so it's simpler to find the right names, but we're not there yet.

Running is described in the README and is now simpler than before.

Unless the swarm-manager has changed too much (can't download the new one with this connection), then `docker-compose up` should now give you the user interface without any extras needed to be installed.  It will connect to your local docker daemon by default IIRC.

Local builds in the pipelines, sharing of volumes, and configuring of environment variables are things we plan to attack in the future.  They're on the wishlist since the workshop @ UoA.

Can you try to run it again with the current build?  I'll try with the new sources by the beginning of next week.

**Comment by cecton** [comment]
It was a bug. Fixed by https://github.com/big-data-europe/mu-swarm-admin-service/commit/83c4bd516d98e28c5dd44befb2b62699ff3c20c8 @madnificent
